language: ruby
rvm:
  - 2.0.0
  - 2.1.1
before_install:
  - gem update bundler
script:
  - bundle exec rspec
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#linyows"
